/**
 * This is the inital schema for the tables 
 
CREATE TABLE messages (
   id          INT GENERATED BY DEFAULT AS IDENTITY,
   text        TEXT NOT NULL,
   userId      TEXT NOT NULL,
   gameId      TEXT NOT NULL,
   createdAt   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
); */