/**
 * This is the inital schema for the tables 
 
CREATE TABLE messages (
    id          INT GENERATED BY DEFAULT AS IDENTITY,
    createdAt   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    gameId      TEXT NOT NULL,
    gameType    TEXT NOT NULL,
    speaker     TEXT NOT NULL,
    text        TEXT NOT NULL
)

*/
